### PR TITLE
Restructure library to combine classes into TinyList

### PR DESCRIPTION
**Pull request by calvintam236**

### CODE REVIEW

**Comment by calvintam236** [comment]
@WieFel can you take a look on this?

**Comment by WieFel** [comment]
> @WieFel can you take a look on this?

Yes, need a bit more time for this...

**Comment by calvintam236** [comment]
> > @WieFel can you take a look on this?
> 
> Yes, need a bit more time for this...

@WieFel Any chance you can take a look?

**Review by WieFel — APPROVED** [review]
Didn't test every of the functions but concerning the code: LGTM

**Pull request merged**
